name: audio_manager
description: A flutter plugin for music playback, including notification handling.
version: 0.8.2
homepage: https://github.com/jeromexiong/audio_manager

environment:
  sdk: ">=2.12.0 <=3.5.3"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: cc.dync.audio_manager
        pluginClass: AudioManagerPlugin
      ios:
        pluginClass: AudioManagerPlugin
      web:
        pluginClass: AudioManagerPlugin
        fileName: audio_manager_web.dart
